/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Navigation: typeof import('./src/components/navigation.vue')['default']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    Search: typeof import('./src/components/search.vue')['default']
    Vortex: typeof import('./src/components/Vortex.vue')['default']
  }
}
